const primaryOrange = '#FF6B35';
const accentBlue = '#4A9FF5';

export const Colors = {
  light: {
    text: '#1A1A2E',
    background: '#F5F5F7',
    tint: primaryOrange,
    icon: '#6B7280',
    tabIconDefault: '#C7C7CC',
    tabIconSelected: accentBlue,
    surface: '#FFFFFF',
    border: 'rgba(0,0,0,0.07)',
    primary: primaryOrange,
    accent: accentBlue,
    secondary: '#8E8E93',
    success: '#34C759',
    danger: '#FF3B30',
    error: '#FF3B30',
    orange: primaryOrange,
    blue: accentBlue,
    green: '#34C759',
    purple: '#AF52DE',
    cardBg: '#FFFFFF',
    heroBackground: '#FFF0E8',
  },
  dark: {
    text: '#F2F2F7',
    background: '#1C1C2E',
    tint: primaryOrange,
    icon: '#AEAEB2',
    tabIconDefault: '#48484A',
    tabIconSelected: accentBlue,
    surface: '#2C2C3E',
    border: 'rgba(255,255,255,0.08)',
    primary: primaryOrange,
    accent: accentBlue,
    secondary: '#8E8E93',
    success: '#30D158',
    danger: '#FF453A',
    error: '#FF453A',
    orange: primaryOrange,
    blue: accentBlue,
    green: '#30D158',
    purple: '#BF5AF2',
    cardBg: '#2C2C3E',
    heroBackground: '#2A1810',
  },
};
